name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ nightly ]
    paths:
      - 'docs/**'
  # Allow manual trigger
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: cd docs && npm ci

      - name: Update browserslist database
        run: cd docs && npx update-browserslist-db@latest

      - name: Prepare directory structure
        run: cd docs && ./prepare-structure.sh

      - name: Verify imports
        run: cd docs && ./verify-imports.sh

      - name: Build
        run: cd docs && npm run build
        env:
          GITHUB_ACTIONS: true

      - name: Fix static asset paths
        run: cd docs && ./fix-static-paths.sh

      - name: Verify build output
        run: |
          if [ -d "docs/out" ]; then
            echo "Build output directory exists"
            ls -la docs/out
          else
            echo "Build output directory does not exist"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 