name: Run Pytest Locally for Nightly Build (on Self-Hosted Runner)

on:
  workflow_dispatch:
  push:
    branches:
      - nightly  # Trigger when changes are pushed to the 'nightly' branch
  pull_request:
    branches:
      - nightly  # Trigger on pull requests to the 'nightly' branch

jobs:
  test:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # You can specify your Python version here

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run Tests with pytest
        run: |
          pytest -s tests  # Run the tests with pytest
